alias la='ls -latr'
alias vi=/usr/bin/vim
alias venv='source /home/pi/mycroft-core/venv-activate.sh'          # start a venv
alias rmvenv=mycroft-venv-deactivate                                # remove a venv
export CPS="/home/pi/mycroft-core/mycroft/skills"                   # common play skill
export DNK="/home/pi/mycroft-dinkum/skills/play-music.mark2"        # Dinkum music
export LOG="/var/log/mycroft"
export MPC="/opt/mycroft/skills/mpc-skill-mike99mac"                # mike99mac's music skill
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/pi/mycroft-core/bin"
export PLA="/opt/mycroft/skills/mycroft-playback-control.mycroftai" # playback control
export SKI="/opt/mycroft/skills"
export SYS="/etc/systemd/system"
export Z="/usr/local/sbin"
