alias la='ls -latr'
alias vi=/usr/bin/vim
export CPS="/home/pi/mycroft-core/mycroft/skills"             # common play skill
export DNK="/home/pi/mycroft-dinkum/skills/play-music.mark2"  # dinkum music skill
export JZ2="/home/pi/mympdplaylist-skill"
export LOG="/var/log/mycroft"
export MCT="/home/pi/mycroft-tools/usr/local/sbin"
export MPC="/opt/mycroft/skills/mpc-skill-mike99mac"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/pi/mycroft-core/bin"
export SKI="/opt/mycroft/skills"
export SYS="/etc/systemd/system"
export Z="/usr/local/sbin"
