#!/bin/bash
#
# gro - GRep Ovos code for a pattern
#
if [ $# = 0 ]; then                        # no args passed
  echo "ERROR: no search pattern passed in"
  echo "Usage: gro SEARCH_PATTERN"
  exit 1
fi
cd ~/.venvs/ovos/lib/python3.10/site-packages/
grep -n "$@" ovos_*/*.py ovos_*/*/*.py ovos_*/*/*/*.py skill_ovos_*/*.py skill_ovos_*/*/*.py | sed "s:^:$HOME/.venvs/ovos/lib/python3.10/site-packages/:g"

