#!/bin/bash
#
# gro - GRep Ovos code for a pattern
#
if [ $# = 0 ]; then                        # no args passed
  echo "ERROR: no search pattern passed in"
  echo "Usage: gro SEARCH_PATTERN"
  exit 1
fi
cd ~/.venvs/ovos/lib/python3.10/site-packages/
grep "$@" ovos_*/*.py ovos_*/*/*.py ovos_*/*/*/*.py # search all python files for the pattern

