#!/bin/bash
#
# install2 - clone ovos-core, create a venv and configure it to run OVOS
#
#+--------------------------------------------------------------------------+
function installOVOS
# Do the work to install ovos-core into a venv 
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  if [ -d ~/ovos-core ]; then              # ovos-core directory exists
    echo -n "~/ovos-core directory exists - do you want to remove it and re-clone? (y/n) "
    read ans
    if [ "$ans" != y -a "$ans" != Y ]; then
      exit 1
    fi
    echo "removing ~/ovos-core directory ..."
    runCmd sudo rm -fr ~/ovos-core
  fi
  
  echo "cloning ovos-core ..."
  cd                                       # cd to home directory
  runCmd git clone https://github.com/OpenVoiceOS/ovos-core
  
  echo "creating a virtual environment ..."
  runCmd cd ~/ovos-core
  runCmd python3 -m venv venv
  
  echo "activating virtual environment ..."
  runCmd source ~/ovos-core/venv/bin/activate

  echo "installing packages with apt-get ..."
  runCmd sudo apt-get install -y build-essential python3-dev swig libssl-dev libfann-dev libpulse-dev libasound2-dev mpg123 portaudio19-dev python3-pyaudio liblapack-dev libopenblas-dev flac
  
# echo "download SuiteSparse code and exporting CVXOPT_SUITESPARSE_SRC_DIR ..." 
# runCmd wget https://people.engr.tamu.edu/davis/SuiteSparse/SuiteSparse-5.4.0.tar.gz
# runCmd tar xf SuiteSparse-5.4.0.tar.gz
# export CVXOPT_SUITESPARSE_SRC_DIR=~/ovos-core/SuiteSparse
# echo "CVXOPT_SUITESPARSE_SRC_DIR = $CVXOPT_SUITESPARSE_SRC_DIR"

  echo "installing wheel with pip install ..."
  runCmd pip install wheel                 # wheel needs to be in place before the next big set

  echo "installing packages with pip install ..."
  runCmd pip install silero tornado ovos-plugin-vlc ovos-ocp-news-plugin ovos-vad-plugin-webrtcvad ovos-stt-plugin-vosk ovos-stt-plugin-chromium

  echo "installing stable version of ovos-core ..."
  runCmd "pip install ovos-core[all]"

  echo "installing date-time skill ..."
  runCmd pip install git+https://github.com/OpenVoiceOS/skill-ovos-date-time.git
  echo "installing weather skill ..."
  pip install git+https://github.com/OpenVoiceOS/skill-ovos-weather.git

  if [ ! -f /etc/systemd/system/mycroft.service ]; then
    echo "copying mycroft.service to /etc/systemd/system ..."
    runCmd sudo cp ~/mycroft-tools/mycroft.service /etc/systemd/system
  fi
  if [ ! -f ~/ovos-core/stop-mycroft.sh ]; then
    echo "making symlink to stop-mycroft.sh ..."
    runCmd ln -s ~/ovos-core/stop-mycroft.sh /usr/local/sbin
  fi
 }                                         # installOVOS()

# main()
source installcommon                       # include common functions
SECONDS=0                                  # reset stopwatch

installOVOS                                # do the work

let min=$SECONDS/60
let sec=$SECONDS%60
if [ $sec -lt 10 ]; then                   # add a leading 0
  sec="0$sec"
fi
echo "successfully installed ovos-core in $min:$sec"

