#!/bin/bash
#
# lsenv - list many aspects of the Mycroft environment
#
#+--------------------------------------------------------------------------+
function usage()
# Give help to the user
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  echo "Name: lspairingcode - List the Mycroft pairing code for your device"
  echo "Usage: lspairingcode [OPTIONS] [PATTERN]"
  echo ""
  echo "OPTIONS:"
  echo "  -h|--help         Give help (this screen)"
  echo "  -v|--verbose      Increase verbosity" 
  echo "  -x|--debug        Print commands and arguments as they are executed"
  exit 51
 }                                         # usage()

#+--------------------------------------------------------------------------+
function parseArgs()
# Parse arguments
# Args: All arguments passed into script
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  while [ -n "$1" ]                        # loop through args passed in
  do
    case "$1" in
      -h|--help)
        usage
        ;;
      -v|--verbose) 
        verbose=2
        ;;
      -x|--debug)                          # turn trace on
         set -vx
         ;;
      *)
	echo "ERROR: Too many arguments: $1"
	usage 
        ;;
    esac
    shift
  done
 }                                         # parseArgs()

#+--------------------------------------------------------------------------+
function listService()
# List the status of one service 
# Arg 1: service to list
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  local theService=$1

  local tempFile=/tmp/fubar
  /usr/sbin/service $theService status > $tempFile 
  grep -q "active (running)" $tempFile 
  if [ $? = 0 ]; then                      # found "active (running)"
    echo "  Service $theService is running"
  else
    echo "  WARNING: Service $theService is not running:"
    cat $tempFile
  fi	  
  /usr/bin/rm $tempFile                    # remove output file 
  # echo                                     # leave some room
 }                                         # listService()

#+--------------------------------------------------------------------------+
function doList()
# List many aspects of the Mycroft environment 
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  echo "Status of the Mycroft stack:"
  listService mycroft
  listService jellyfin
  listService pulseaudio
  /usr/local/sbin/lstemp                   # show the temp of the RasPi
 }                                         # doList()

#+--------------------------------------------------------------------------+
# Global variables"
verbose=1                                  # verbosity

# main()
parseArgs $@                                # parse arguments
doList                                      # list the requested output 

