#!/bin/bash
#
# lsmycrofttools - show a summary of all tools/scripts in mycroft-tools 
#
#+--------------------------------------------------------------------------+
function usage()
# Give help to the user
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  echo                                     # leave some room
  echo "Name: lsmycrofttools - Show a summary of all tools/scripts in mycroft-tools" 
  echo "Usage: lsmycrofttools [OPTIONS]"
  echo ""
  echo "OPTIONS:"
  echo "  -h|--help         Give help (this screen)"
  echo "  -l|--long         Add additional information"
  echo "  -x|--debug        Print commands and arguments as they are executed"
  exit 51
 }                                         # usage()

#+--------------------------------------------------------------------------+
function parseArgs()
# Parse arguments
# Args: All arguments passed into script
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  while [ -n "$1" ]                        # loop through args passed in
  do
    case "$1" in
      -h|--help)
        usage
        ;;
      -l|--long)
         outputType=long 
         ;;
      -x|--debug)                          # turn trace on
         set -vx
         ;;
      *)
	echo "ERROR: Too many arguments: $1"
	exit 4 
        ;;
    esac
    shift
  done
 }                                         # parseArgs()

#+--------------------------------------------------------------------------+
function listTools()
# List all tools in the mycroft-tools repo 
# Args: 
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  if [ "$outputType" = long ]; then        # long listing
    echo "Help for all scripts:"
    for i in lsenv lsintent  lsmycrofttools lspairing lsskill lsskills lstemp lsvocab testplay testrecord; do
      $i -h                                # give help for this script	    
      echo
    done	    
    echo "---------------------------------------------------------"	  
  fi

  # one liner for all scripts in repo
  echo "lsenv          - List the Mycroft environment - what services are running?"
  echo "lsintent       - List Mycroft intents - What can I say?"
  echo "lsmycrofttools - List all tools in the mycroft-tools repo (this file)" 
  echo "lspairing      - List the Mycroft pairing code to pair a new device with mycroft.ai"
  echo "lsskill        - List intent, etc files of one Mycroft skills" 
  echo "lsskills       - List Mycroft skills installed or not installed"
  echo "lstemp         - Report the temperature of the Raspberry Pi"
  echo "lsvocab        - List Mycroft vocabularies - what are the pieces of requests recognized?"
  echo "testplay       - Play back a recorded file to test your speakers"
  echo "testrecord     - Record for a short while and save to a file to test your microphone"
 }                                         # listTools()

#+--------------------------------------------------------------------------+
# Global variables"
outputType="short"                          # short or long listing 

# main()
parseArgs $@                                # parse arguments
listTools                                   # list all tools 

