#!/bin/bash
#
# lstemp - show the temperature of the Raspberry Pi based on 
#          the file /sys/class/thermal/thermal_zone0/temp
#
tempFile="/sys/class/thermal/thermal_zone0/temp"
if [ ! -f $tempFile ]; then                # file not found
  echo "ERROR: did not find $tempFile"
  exit 1
fi  
theTemp=`cat /sys/class/thermal/thermal_zone0/temp` # in thousdandths of degrees celcius
let theTemp=$theTemp/1000                  # convert to degrees Celcius
let tempF=$theTemp*9/5+32                  # convert to degrees Farenheit
echo "Current temperature of the Raspberry Pi: ${theTemp}C / ${tempF}F"
