#!/bin/bash
#
# temp - show the temperature of the Raspberry Pi based on 
#        the file /sys/class/thermal/thermal_zone0/temp
#
theTemp=`cat /sys/class/thermal/thermal_zone0/temp` # in thousdandths of degrees celcius
let theTemp=$theTemp/1000                  # convert to degrees Celcius
# convert to Farenheit
let tempF=$theTemp*9/5
let tempF=$tempF+32
echo "Current temperature of the Raspberry Pi: ${theTemp}C / ${tempF}F"
