#!/bin/bash
#
# tmpfsmnt - mount tmpfs file systems over log file directories 
#
mount -t tmpfs -o size=100m,mode=1777 tmpfs /var/log

# change user in logDir if it is not 'pi'
logDir=/home/pi/.local/state/mycroft
if [ ! -d $logDir ];
  cmd="mkdir -p $logDir"
  $cmd
  rc=$?
  if [ "$rc" != 0 ]; then
    echo "ERROR: $cmd returned $rc"
    exit 1
  fi
fi
mount -t tmpfs -o size=100m,mode=1777 tmpfs /home/pi/.local/state/mycroft

