#!/bin/bash
#
# uninstallmycroft - completely remove Mycroft 
#
echo "WARNING - this will completely remove Mycroft!!!"
echo "ARE YOU SURE you want to do this? (y|N)"
read ans
ans=`echo $ans | tr [:upper:] [:lower:]`
if [ "$ans" != y ]; then
  exit 1
fi
if [ ! -d /opt/mycroft ]; then 
  echo "ERROR: /opt/mycroft is not a directory"
  exit 1
fi
#if [ ! -d ~/mycroft-core ]; then
#  echo "ERROR: ~/mycroft-core is not a directory"
#  exit 1
#fi
for nextDir in ~/.mycroft /opt/mycroft ~/mycroft-core /etc/mycroft/mycroft.conf /var/log/mycroft/
do
  echo "Removing: $nextDir ..."
  sudo rm -rf $nextDir
done 
